version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: memory-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 456
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./express-backend
    container_name: memory-backend
    environment:
      - MONGO_URI=mongodb://root:456@memory-mongo:27017/memory_game?authSource=admin
      - PORT=3000
      - FRONTEND_PORT=80
      - HOST=memory-frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./express-backend/public/uploads:/app/public/uploads

  frontend:
    build: ./vue-frontend
    container_name: memory-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://localhost:3000

volumes:
  mongodb_data:
